### ISSUE TITLE
Think about frontends.

### ISSUE THREAD

**Issue by mickys** [deb0x/deb0x-faberweb3#102]
When writing smart contracts, think about the number of calls you're going to make to get all the data you need in order to display the relevant information a user requires.

Implement 1 view function which gathers everything required for your frontend. 
Either for each contract, or write a view contract that does it.

**Comment by dappcoder** [comment]
@mickys thanks for the feedback. There is a contract implemented specifically for retrieving state related data from the contract -  Deb0xViews.sol. Other than that, event log data is fetched through an indexing service.
